### ISSUE TITLE
Some Knime workflow examples using the "Keras Network Learner" node do not work

### ISSUE THREAD

**Issue by htreutlein1** [PacktPublishing/Codeless-Deep-Learning-with-KNIME#2]
This is a very informative book.  However, some of the example workflows that involve the "Keras Network Learner" do not work, e.g. the training workflow in Chapter 6, or Generate Fairy tales in Chapter 7. At least in Knime 4.4 under macos 11.5.2 I get the following errors:

WARN  Keras Network Learner 0:85       The number of rows of the input training data table (41291) is not a multiple of the selected training batch size (256). Thus, the last batch of each epoch will continue at the beginning of the training data table after reaching its end. You can avoid that by adjusting the number of rows of the table or the batch size if desired.
WARN  Keras Network Learner 0:85       /Users/herbert/Software/A/anaconda3/envs/py3_knime_dl/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
ERROR Keras Network Learner 0:85       java.lang.Exception: Failed to receive message from Python or forward received message.
ERROR Keras Network Learner 0:85       Execute failed: An error occured during training of the Keras deep learning network. See log for details.

This is a pity since ffor a beginner it is almost impossible to find out what causes the errors, and makes the book a lot less useful.  In the end, a python script might be better to use?  

Cheers,
Herbert

**Comment by Kathrin-Me** [comment]
Hi Herbert, 

recently we encountered that there is sometimes an issue when training a neural network with an LSTM layer on Mac, which is caused due to the environment setup. Our developers fixed this issue already in the newest KNIME Version 4.4.1, which we released last week. Can you please do me a favor and
1. Update your KNIME Analytics Platform to 4.4.1
2. Create a new python environment for deep learning via the KNIME Preference page
3. Try to execute the workflows of chapter 6 and 7?
4. Please let me know whether that worked :) 

Thank you
Kathrin

**Comment by htreutlein1** [comment]
Hi Kathrin,

Yes, that worked.  Thank you so much for your help.

Best wishes,
Herbert

**Comment by Kathrin-Me** [comment]
Hi Herbert,

brilliant, thank you for the update! 

Cheers,
Kathrin
